### ISSUE TITLE
Change to open source license?

### ISSUE THREAD

**Issue by dpriskorn** [Data-Engineering-and-Semantics/refb#1]
The current license is not made for software and might be unnecessary restrictive.

**Comment by Daniel-Mietchen** [comment]
Yes, changing this to an open license would seem reasonable.

**Comment by csisc** [comment]
Sure. I will change the license to CC0.

**Comment by csisc** [comment]
May be I should change it to MIT.

**Comment by dpriskorn** [comment]
I personally prefer GPLv3+. Most of the software I use is under that license. 
See 
https://www.youtube.com/watch?v=zzmNA2iySEs
https://opensource.com/article/17/2/decline-gpl
https://lukesmith.xyz/articles/why-i-use-the-gpl-and-not-cuck-licenses

**Comment by csisc** [comment]
Done. I will be having a presentation on this topic at the 2021 CC Summit next week. I am an advocate of using Creative Commons as a universal license for all distinct types of open resources. However, I agree that GPL is better as a license for source codes. I will be working on refining the source code during the next few weeks to substitute QuickStatements API by Wikidata Integrator and enhance the layout of the code.
