### ISSUE TITLE
Migrate to newest WBI version? 

### ISSUE THREAD

**Issue by dpriskorn** [Data-Engineering-and-Semantics/refb#4]
Hi, I just want to tip you to look at the source of ItemSubjector to see v0.12 of WBI in action.
It seems to work fine, so I suggest you go with that if you feel like it.

**Comment by dpriskorn** [comment]
Now that we both use GPL you can copy paste the whole wikidata.py model if you want 😃
I'm planning to separate it out later on, but for now I just copy it to new projects and improve as I go.

**Comment by csisc** [comment]
Done. I have improved the bot.
